### PR TITLE
Add prettier/eslint, rewrite extension.ts, change shortcuts, and other cleanups

### PR DESCRIPTION
**Pull request by mk12**
This is a stack of five changes to make this extension do what I want. I've made it in separate commits so they can be reviewed in turn. Feel free to accept some or all of them.

### 1. Add prettier, eslint, and minor fixes

* Format the code with **prettier**.
* Lint the code with **eslint**, configured for TypeScript and prettier.
* Standardize on 4-space indentation in JSON files.
* Update some npm packages.
* Use tsconfig.json settings recommended for VS Code extensions.
* Change .vscode/launch.json to match VS Code sample extension.
* Generate output JS file and sourcemap in **out/extension.js** instead of in src/.
* Show an error message for "Execute Selection" which isn't implemented.
* Clean up the README formatting and wording.

### 2. Refactor and clean up extension

* **Implement "Execute Selection"**.
* **Rewrite the backslash command** to be more reliable. ~~Remove the "pending" logic, since `\\d` should result in `\↕`.~~
* **Create the REPL in the terminal panel**, not in an editor (which was annoying because it covered the current editor).
* When executing code requires creating a new REPL, **delay for 500ms** (customizable) to wait for BQN to be ready, otherwise input gets messed up in my experience. Also delay 50ms before sending the newline after an `)ex` command for similar reasons.
* **Start the REPL in the current file's directory**, rather than the project directory (default), so that imports work correctly.
* For execution commands, **keep focus in the editor**, but for the "Create BQN REPL" command, focus the terminal.
* When advancing to the next line, **skip over blank lines and comments**.
* Use title case for "BQN: Convert To Symbol".
* Remove unused codeLensProvider capability.
* Remove semantic highlighting, which didn't work and was causing errors in the logs (seems to have been copied from some sample code).
* Remove `// #region` folding support which doens't make sense in BQN.
* Remove some characters from autoCloseBefore which looked like they didn't belong (based on the docs, "typically the set of characters which can not start an expression").

### 3. Improve keyboard shortcuts

* **Use Ctrl+Enter for both "Execute Line and Advance" and "Execute Selection"**, based on whether text is selected or not. There is no need for separate shortcuts (also, Ctrl+E which was used before conflicts with the default shortcut for jumping to the end of the line, which I use heavily since it's supported everywhere in macOS).
* Remove the "cbqn" default, since "bqn.executablePath" already is already defaulted to "bqn" later in package.json.
* Remove the "terminal.integrated.enablePersistentSessions" setting. It feels like an overreach for a BQN extension to change this globally. And it's already on by default in VS Code anyway.

### 4. Add clearImportsAndLoadScript

* Add a new command `clearImportsAndLoadScript` bound to Ctrl+Shift+L that clears the import cache before loading the script.

### 5. Add saveBeforeLoadScript config setting

* This makes it save the document before loading. I find this more convenient, but made it default to false in case it's unexpected for anyone.

### CODE REVIEW

**Comment by razetime** [comment]
Wow. I only have one problem, `\\d` should give `\d`, since every input method maps backslash to backslash. Otherwise i think this is amazing and I'll merge it after a test soon.

**Comment by mk12** [comment]
Ah, yeah that makes sense. I'll amend it so that `\\` produces a single backslash. (My goal in rewriting that logic was just to make it work consistently, since before it seemed to not work sometimes though I couldn't find an exact repro.)

**Comment by mk12** [comment]
All right, I changed the backslash behavior and also added a 5th commit that adds a saveBeforeLoadScript setting.

**Comment by razetime** [comment]
I am getting a strange error when i run `vsce` on the new code:

```
$ vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> bqn-language@0.1.0 vscode:prepublish
> npm run compile


> bqn-language@0.1.0 compile
> tsc -p ./

src/extension.ts:123:21 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(Promise<void> | Thenable<boolean>)[]' is not assignable to parameter of type 'Iterable<void | PromiseLike<void>>'.
      The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
        Type 'IteratorResult<Promise<void> | Thenable<boolean>, any>' is not assignable to type 'IteratorResult<void | PromiseLike<void>, any>'.
          Type 'IteratorYieldResult<Promise<void> | Thenable<boolean>>' is not assignable to type 'IteratorResult<void | PromiseLike<void>, any>'.
            Type 'IteratorYieldResult<Promise<void> | Thenable<boolean>>' is not assignable to type 'IteratorYieldResult<void | PromiseLike<void>>'.
              Type 'Promise<void> | Thenable<boolean>' is not assignable to type 'void | PromiseLike<void>'.
                Type 'Thenable<boolean>' is not assignable to type 'void | PromiseLike<void>'.
                  Type 'Thenable<boolean>' is not assignable to type 'PromiseLike<void>'.
                    Types of property 'then' are incompatible.
                      Type '{ <TResult>(onfulfilled?: ((value: boolean) => TResult | Thenable<TResult>) | undefined, onrejected?: ((reason: any) => TResult | Thenable<TResult>) | undefined): Thenable<...>; <TResult>(onfulfilled?: ((value: boolean) => TResult | Thenable<...>) | undefined, onrejected?: ((reason: any) => void) | undefined): Thena...' is not assignable to type '<TResult1 = void, TResult2 = never>(onfulfilled?: ((value: void) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined) => PromiseLike<...>'.
                        Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
                          Type '((value: void) => any) | null | undefined' is not assignable to type '((value: boolean) => any) | undefined'.
                            Type 'null' is not assignable to type '((value: boolean) => any) | undefined'.

123   await Promise.all(tasks);
                        ~~~~~

  node_modules/typescript/lib/lib.es2015.iterable.d.ts:226:5
    226     all<T>(values: Iterable<T | PromiseLike<T>>): Promise<T[]>;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.

Found 1 error.

 ERROR  npm failed with exit code 2
```

**Comment by mk12** [comment]
Huh, `vsce package` worked for me earlier. I can investigate later today. Maybe try `npm install` first if you haven’t already (since one of my commits updates some dependencies)?

**Comment by mk12** [comment]
Ok, yes it's because I upgraded `typescript` from ^3.9.10 to ^4.9.4. I reproduced your error when I tried to compile after reverting the `typescript` and `@types/node` dependencies back to their old versions. If you `npm install` first, then `vsce package` should succeed.

**Comment by razetime** [comment]
ah, make sense. i'll get it published today.

**Pull request merged**
